# Generated by Django 4.2.1 on 2023-05-30 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='05:39', unique=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('about', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=128)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(blank=True, choices=[('Dushanba', 'Dushanba'), ('Seshanba', 'Seshanba'), ('Chorshanba', 'Chorshanba'), ('Pashanba', 'Pashanba'), ('Juma', 'Juma'), ('Shanba', 'Shanba'), ('Yakshanba', 'Yakshanba')], default=3, max_length=20, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('phone_number', models.CharField(blank=True, max_length=128)),
                ('step', models.IntegerField(blank=True, default=0, null=True)),
                ('language', models.CharField(default='uz', max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('busy_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.weekdays')),
                ('busy_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.daytimes')),
                ('responsible_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.doctor')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='availabe_times',
            field=models.ManyToManyField(to='bot.weekdays'),
        ),
        migrations.AddField(
            model_name='daytimes',
            name='week_day',
            field=models.ManyToManyField(to='bot.weekdays'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('consultation_type', models.CharField(default='off', max_length=25)),
                ('urgent', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('card', models.CharField(blank=True, max_length=250)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['first_name'], name='bot_doctor_first_n_c89323_idx'),
        ),
    ]
