# Generated by Django 4.2.1 on 2023-07-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='83557ec4-729a-4843-bda0-81be80efeecf', max_length=256),
        ),
    ]
