# Generated by Django 4.2.1 on 2023-05-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meettime',
            name='end_time',
            field=models.TimeField(default='11:59:51'),
        ),
        migrations.AlterField(
            model_name='meettime',
            name='start_time',
            field=models.TimeField(default='11:59:51'),
        ),
    ]
