# Generated by Django 4.2.1 on 2023-06-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='source',
            field=models.CharField(choices=[('bot', 'Bot orqali'), ('web', 'Admin panel orqali')], default='web', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user_id',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='11:28', unique=True),
        ),
    ]
