# Generated by Django 4.2.1 on 2023-06-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='7b8a796c-7fce-4bad-b247-deb85e450648', max_length=256),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='09:22', unique=True),
        ),
    ]
