# Generated by Django 4.2.1 on 2023-06-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='19:07', unique=True),
        ),
        migrations.AddConstraint(
            model_name='docworkday',
            constraint=models.UniqueConstraint(fields=('doctor', 'day'), name='unique_doctor_day'),
        ),
    ]
