# Generated by Django 4.2.1 on 2023-07-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_doctor_doc_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='d564ac6e-efa8-49b1-a7fa-e10898b7b50a', max_length=256),
        ),
    ]
