# Generated by Django 4.2.1 on 2023-06-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_doctor_doc_token_alter_time_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='1fba1d39-1786-4c61-b17e-cceb925e5c6c', max_length=256),
        ),
    ]
