# Generated by Django 4.2.1 on 2023-06-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_time_start_time_docworkday_unique_doctor_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='19:13', unique=True),
        ),
    ]
