# Generated by Django 4.2.1 on 2023-05-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='language',
            field=models.CharField(choices=[('UZ', 'Кирилча'), ('uz', "O'zbekcha")], default='uz', max_length=10),
        ),
    ]
