# Generated by Django 4.2.1 on 2023-06-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_doctor_doc_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='a8054d5a-7bd5-4df7-8b55-54b82364c560', max_length=256),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='16:04', unique=True),
        ),
    ]
