# Generated by Django 4.2.1 on 2023-07-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_doctor_doc_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='b8562b35-51ea-4507-aac2-43202cded92f', max_length=256),
        ),
    ]
