# Generated by Django 4.2.1 on 2023-06-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_time_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='urgent',
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='19:25', unique=True),
        ),
    ]
