# Generated by Django 4.2.1 on 2023-05-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_meettime_end_time_alter_meettime_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='meettime',
            name='end_time',
            field=models.TimeField(default='13:33:59'),
        ),
        migrations.AlterField(
            model_name='meettime',
            name='start_time',
            field=models.TimeField(default='13:33:59'),
        ),
    ]
