# Generated by Django 4.2.1 on 2023-05-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_patient_status_alter_meettime_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.AddField(
            model_name='patient',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meettime',
            name='end_time',
            field=models.TimeField(default='13:34:54'),
        ),
        migrations.AlterField(
            model_name='meettime',
            name='start_time',
            field=models.TimeField(default='13:34:54'),
        ),
    ]
