# Generated by Django 4.2.1 on 2023-06-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_doctor_doc_id_alter_time_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qrcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='12:38', unique=True),
        ),
    ]
