# Generated by Django 4.2.1 on 2023-06-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_doctor_doc_token_alter_time_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='d94fe994-bc74-4ad4-b56c-ff1d99a48620', max_length=256),
        ),
    ]
