# Generated by Django 4.2.1 on 2023-05-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_patient_appointment_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='complaint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
