# Generated by Django 4.2.1 on 2023-06-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_doctor_qrcode_alter_time_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='qrcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='14:41', unique=True),
        ),
    ]
