# Generated by Django 4.2.1 on 2023-05-29 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_appointment_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('about', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=128)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='card',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='MeetTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(blank=True, choices=[('du', 'Dushanba'), ('se', 'Seshanba'), ('ch', 'Chorshanba'), ('pa', 'Pashanba'), ('ju', 'Juma'), ('sh', 'Shanba'), ('ya', 'Yakshanba')], default=3, max_length=10)),
                ('start_time', models.TimeField(default='10:04:39')),
                ('end_time', models.TimeField(default='10:04:39')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.doctor')),
            ],
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['first_name'], name='bot_doctor_first_n_c89323_idx'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.doctor'),
        ),
    ]
