# Generated by Django 4.2.1 on 2023-05-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_doctor_appointment_card_appointment_price_meettime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meettime',
            name='end_time',
            field=models.TimeField(default='10:04:58'),
        ),
        migrations.AlterField(
            model_name='meettime',
            name='start_time',
            field=models.TimeField(default='10:04:58'),
        ),
    ]
