# Generated by Django 4.2.1 on 2023-06-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_doctor_doc_token_alter_time_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('bot', 'Bot orqali'), ('web', 'Admin panel orqali')], default='web', max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='65a0e27f-d175-47b9-9716-3a0aa7443bb6', max_length=256),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='17:01', unique=True),
        ),
    ]
