# Generated by Django 4.2.1 on 2023-06-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_doctor_doc_token_alter_time_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='a01f6738-e2ed-4f82-b314-ac89a5cfccc6', max_length=256),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='16:04', unique=True),
        ),
    ]
