# Generated by Django 4.2.1 on 2023-05-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_meettime_end_time_alter_meettime_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meettime',
            name='end_time',
            field=models.TimeField(default='10:05:11'),
        ),
        migrations.AlterField(
            model_name='meettime',
            name='start_time',
            field=models.TimeField(default='10:05:11'),
        ),
    ]
