# Generated by Django 4.2.1 on 2023-06-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_appointment_type_alter_doctor_doc_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='show_img_preview',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='d2700db4-c58b-4597-8060-01d81504a1dd', max_length=256),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='17:49', unique=True),
        ),
    ]
