# Generated by Django 4.2.1 on 2023-06-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_doctor_show_img_preview_alter_doctor_doc_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('current', models.IntegerField()),
                ('message_id', models.BigIntegerField()),
                ('admin_id', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='7241fbab-2805-479c-b621-79eadd9f0ff6', max_length=256),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='17:12', unique=True),
        ),
    ]
