# Generated by Django 4.2.1 on 2023-06-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_letter_alter_doctor_doc_token_alter_time_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='ab073f10-952b-451e-bd0b-d672a96d50f3', max_length=256),
        ),
    ]
