# Generated by Django 4.2.1 on 2023-06-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_doctor_doc_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='5adf12f4-9636-4f7e-924a-bfd0c26048d7', max_length=256),
        ),
    ]
