# Generated by Django 4.2.1 on 2023-06-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_doctor_doc_token_alter_letter_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='ccb65cee-9e83-4976-a18b-d35bbbb6f8c8', max_length=256),
        ),
    ]
