# Generated by Django 4.2.1 on 2023-06-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_doctor_doc_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_token',
            field=models.CharField(default='628c26bd-d3f0-40b0-8389-c027a925068b', max_length=256),
        ),
    ]
