# Generated by Django 4.2.1 on 2023-05-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_daytimes_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytimes',
            name='week_day',
        ),
        migrations.AddField(
            model_name='weekdays',
            name='day_time',
            field=models.ManyToManyField(to='bot.daytimes'),
        ),
        migrations.AlterField(
            model_name='daytimes',
            name='start_time',
            field=models.TimeField(default='06:05'),
        ),
    ]
