# Generated by Django 4.2.1 on 2023-05-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_remove_daytimes_week_day_weekdays_day_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytimes',
            name='start_time',
            field=models.TimeField(default='06:06'),
        ),
    ]
