# Generated by Django 4.2.1 on 2023-05-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_times_remove_doctor_availabe_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='start_time',
            field=models.TimeField(default='06:59', unique=True),
        ),
    ]
