# Generated by Django 4.2.1 on 2023-05-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_time_weekday_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='availabe_days',
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='08:30', unique=True),
        ),
    ]
