# Generated by Django 4.2.1 on 2023-05-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_remove_doctor_availabe_days_alter_time_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='week_day',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='responsible_doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('applied', 'Ariza topshirildi'), ('successfull', 'Qabul yakunlandi'), ('cancel', 'Bekor qilindi'), ('unsuccessfull', 'Bajarilmadi')], default='applied', max_length=15),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='08:49', unique=True),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='week_day',
            field=models.CharField(choices=[('monday', 'Dushanba'), ('tuesday', 'Seshanba'), ('wednesday', 'Chorshanba'), ('thursday', 'Pashanba'), ('friday', 'Juma'), ('saturday', 'Shanba'), ('sunday', 'Yakshanba')], default=3, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='DocWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.weekday')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.doctor')),
                ('times', models.ManyToManyField(to='bot.time')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='docworkday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.docworkday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.time'),
            preserve_default=False,
        ),
    ]
