# Generated by Django 4.2.1 on 2023-05-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_remove_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='active',
        ),
        migrations.RemoveField(
            model_name='weekday',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='08:51', unique=True),
        ),
    ]
