# Generated by Django 4.2.1 on 2023-05-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_remove_weekday_active_remove_weekday_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='weekday',
            name='updated_at',
        ),
    ]
