# Generated by Django 4.2.1 on 2023-05-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_remove_weekday_created_at_remove_weekday_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='08:52', unique=True),
        ),
    ]
