# Generated by Django 4.2.1 on 2023-05-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_alter_time_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='busy_time',
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='08:58', unique=True),
        ),
    ]
