# Generated by Django 4.2.1 on 2023-05-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_remove_patient_busy_time_alter_time_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='09:01', unique=True),
        ),
    ]
