# Generated by Django 4.2.1 on 2023-05-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_alter_time_start_time_alter_weekday_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='10:23', unique=True),
        ),
    ]
