# Generated by Django 4.2.1 on 2023-05-31 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_alter_time_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='docworkday',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bot.docworkday'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bot.time'),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='12:28', unique=True),
        ),
    ]
